// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "detectorDuplicateRows": boolean;
      "detectorNearDuplicateRows": boolean;
      "detectorDuplicateNumericSequences": boolean;
      "detectorBenfordDeviation": boolean;
      "detectorSecondDigitBenfordDeviation": boolean;
      "detectorTerminalDigitPreference": boolean;
      "detectorRoundingHeaping": boolean;
      "detectorPValueThresholdClustering": boolean;
      "detectorRepeatedNumericColumns": boolean;
      "detectorUniformNumericColumns": boolean;
      "detectorLowVarianceNumericColumns": boolean;
      "detectorInvalidPercentages": boolean;
      "detectorInvalidPValues": boolean;
    };
  }
}
